
; $Name:Новая тема$
; модификация темы fantasy
include = fantasy
scr.gfx.mode = float

win.x = 60
win.y = 320
win.w = 554
win.h = 208
win.ways.mode = bottom
scr.gfx.x = 84
scr.gfx.y = 74
scr.gfx.w = 480
scr.gfx.h = 240

inv.x = 660
